[Service]
Environment=RESEARKA_V2_PUBLIC_ACTIVE_KEY_LIMIT=200000
Environment=RESEARKA_V2_PUBLIC_REGISTRATIONS_PER_DAY=10000
Environment=RESEARKA_V2_PUBLIC_REGISTRATIONS_PER_IP_PER_DAY=100
Environment=RESEARKA_V2_PUBLIC_KEY_DAILY_LIMIT=10
Environment=RESEARKA_V2_PUBLIC_REGISTRATION_ENABLED=1
